server:
  port: 8080

spring:
  application:
    name: k8s-coach

app:
  name: K8s Coach
  version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
