apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployable-spring-site
  namespace: spring-demo
  labels:
    app: deployable-spring-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployable-spring-site
  template:
    metadata:
      labels:
        app: deployable-spring-site
    spec:
      containers:
        - name: app
          image: deployable-spring-site:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
